#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Karmaville::Application.load_tasks

desc "setkarma"
task :set_karma => :environment do

  User.find_in_batches(start: 0, batch_size: 1000) do |group|
    group.each { |user| user.update_attribute(:totalkarma,  user.karma_points.sum(:value)) }
  end

end

